name: "Merge Dependabot PR"

on:
  pull_request:

jobs:
  mvn-test:
    uses: ./.github/workflows/callable-mvn.yml
    with:
      mvn-stage: test
  # TODO necessary?
  codeql:
    needs: mvn-test
    uses: ./.github/workflows/callable-codeql.yml
  merge:
    needs: mvn-test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Merge dependabot PR
        uses: fastify/github-action-merge-dependabot@v3
        with:
          skip-verification: true
