name: Merge Dependabot PR

on:
  pull_request:

jobs:

  test:
    uses: ./.github/workflows/callable-mvn.yml
    with:
      mvn-stage: test

  codeql:
    needs: test
    uses: ./.github/workflows/callable-codeql.yml

  automerge:
    needs: codeql
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Merge dependabot PR
        uses: fastify/github-action-merge-dependabot@v3
        with:
          skip-verification: true
