name: Merge Dependabot PR

on:
  pull_request:
    types:
      - opened

jobs:
  merge:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Merge Dependabot PR
        uses: juliangruber/merge-pull-request-action@v1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1
          method: squash # merge rebase