name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  library-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: derBobby/java-pipelines@main
      with:
        path: .github/workflows/library-test-and-deploy.yml